version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: mjv
      MYSQL_USER: root
      MYSQL_PASSWORD: mjv-teste
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - /var/lib/mysql
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: mysql
    links:
      - mysql:mysql
    depends_on:
      - mysql
    expose:
      - 3000